// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNKbDCVkY-m6qn6BGxerd_GmKx4UJOZ9M',
    appId: '1:411633933069:web:c5faa8cf3cda9b5ea76e44',
    messagingSenderId: '411633933069',
    projectId: 'bookapp-1bcaa',
    authDomain: 'bookapp-1bcaa.firebaseapp.com',
    storageBucket: 'bookapp-1bcaa.appspot.com',
    measurementId: 'G-FHXWZWJ4E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCVCQ7rl9Xu8SipPeE4rRk3iccpb4sDXw',
    appId: '1:411633933069:android:4124e5f6debd3695a76e44',
    messagingSenderId: '411633933069',
    projectId: 'bookapp-1bcaa',
    storageBucket: 'bookapp-1bcaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVwrXvpEf1vRAhtdttsRECzNVRMlQI0G4',
    appId: '1:411633933069:ios:8ad7f670d1372ff9a76e44',
    messagingSenderId: '411633933069',
    projectId: 'bookapp-1bcaa',
    storageBucket: 'bookapp-1bcaa.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVwrXvpEf1vRAhtdttsRECzNVRMlQI0G4',
    appId: '1:411633933069:ios:25376b8685796851a76e44',
    messagingSenderId: '411633933069',
    projectId: 'bookapp-1bcaa',
    storageBucket: 'bookapp-1bcaa.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
